### ISSUE TITLE
../stairsにあるstore successのスコアオブジェクトがload_onceに記載されていない

### ISSUE THREAD

**Issue by nea-c** [Irohamaru/SmartMotion#1]
多分記述ミス。
配布データパックに移行する際に変更し忘れたものと考えられる。

&nbsp;

### タイトル編集しすぎた

**Comment by Irohamaru** [comment]
[古いスコア名が残っていたのを修正](https://github.com/Irohamaru/SmartMotion/commit/890508e813b05d1d5a5ee71ec868f2ed03311285)
